{
 "title": "Go Microservice Boilerplate",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average gRPC Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_request_duration_seconds_sum[1m])) / sum(rate(grpc_request_duration_seconds_count[1m]))",
     "legendFormat": "avg duration"
    }
   ]
  },
  {
   "title": "gRPC Request Latency (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_request_duration_seconds_bucket[5m])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Requests per Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(grpc_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total gRPC Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(grpc_requests_total)", "legendFormat": "__auto" }
   ]
  }
 ]
}