// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/hello_world/hello_world.proto

package hello_world

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_proto_hello_world_hello_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_world_hello_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_world_hello_world_proto_rawDescGZIP(), []int{0}
}

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_proto_hello_world_hello_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_world_hello_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_proto_hello_world_hello_world_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SayHelloResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_hello_world_hello_world_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_world_hello_world_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_hello_world_hello_world_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_hello_world_hello_world_proto protoreflect.FileDescriptor

const file_proto_hello_world_hello_world_proto_rawDesc = "" +
	"\n" +
	"#proto/hello_world/hello_world.proto\x12\vhello_world\"\x11\n" +
	"\x0fSayHelloRequest\"S\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12%\n" +
	"\x04user\x18\x02 \x01(\v2\x11.hello_world.UserR\x04user\"@\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email2R\n" +
	"\aGreeter\x12G\n" +
	"\bSayHello\x12\x1c.hello_world.SayHelloRequest\x1a\x1d.hello_world.SayHelloResponseBJZHgithub.com/SagarMaheshwary/go-microservice-boilerplate/proto/hello_worldb\x06proto3"

var (
	file_proto_hello_world_hello_world_proto_rawDescOnce sync.Once
	file_proto_hello_world_hello_world_proto_rawDescData []byte
)

func file_proto_hello_world_hello_world_proto_rawDescGZIP() []byte {
	file_proto_hello_world_hello_world_proto_rawDescOnce.Do(func() {
		file_proto_hello_world_hello_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hello_world_hello_world_proto_rawDesc), len(file_proto_hello_world_hello_world_proto_rawDesc)))
	})
	return file_proto_hello_world_hello_world_proto_rawDescData
}

var file_proto_hello_world_hello_world_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_hello_world_hello_world_proto_goTypes = []any{
	(*SayHelloRequest)(nil),  // 0: hello_world.SayHelloRequest
	(*SayHelloResponse)(nil), // 1: hello_world.SayHelloResponse
	(*User)(nil),             // 2: hello_world.User
}
var file_proto_hello_world_hello_world_proto_depIdxs = []int32{
	2, // 0: hello_world.SayHelloResponse.user:type_name -> hello_world.User
	0, // 1: hello_world.Greeter.SayHello:input_type -> hello_world.SayHelloRequest
	1, // 2: hello_world.Greeter.SayHello:output_type -> hello_world.SayHelloResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_hello_world_hello_world_proto_init() }
func file_proto_hello_world_hello_world_proto_init() {
	if File_proto_hello_world_hello_world_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hello_world_hello_world_proto_rawDesc), len(file_proto_hello_world_hello_world_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hello_world_hello_world_proto_goTypes,
		DependencyIndexes: file_proto_hello_world_hello_world_proto_depIdxs,
		MessageInfos:      file_proto_hello_world_hello_world_proto_msgTypes,
	}.Build()
	File_proto_hello_world_hello_world_proto = out.File
	file_proto_hello_world_hello_world_proto_goTypes = nil
	file_proto_hello_world_hello_world_proto_depIdxs = nil
}
